const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('acgplan', {
  getLibraryInfo: () => ipcRenderer.invoke('library:getInfo'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setLibraryRoot: (libraryRoot) => ipcRenderer.invoke('settings:setLibraryRoot', libraryRoot),
  selectLibraryRoot: () => ipcRenderer.invoke('settings:selectLibraryRoot'),
  openLibraryRoot: () => ipcRenderer.invoke('library:openRoot'),
  getCatalog: () => ipcRenderer.invoke('catalog:get'),
  saveCatalog: (catalog) => ipcRenderer.invoke('catalog:save', catalog),
  importCatalogAsset: (assetType, collectionId) => ipcRenderer.invoke('catalog:importAsset', assetType, collectionId),
  saveCollectionIcon: (collectionId, imageDataUrl, fileName) =>
    ipcRenderer.invoke('catalog:saveCollectionIcon', collectionId, imageDataUrl, fileName),
  selectImageForCatalogCrop: () => ipcRenderer.invoke('catalog:selectImageForCrop'),
  saveCroppedWallpaper: (imageDataUrl, fileName) => ipcRenderer.invoke('catalog:saveCroppedWallpaper', imageDataUrl, fileName),
  getStoryCatalog: () => ipcRenderer.invoke('stories:getCatalog'),
  saveStoryCatalog: (catalog) => ipcRenderer.invoke('stories:saveCatalog', catalog),
  getStories: () => ipcRenderer.invoke('stories:getAll'),
  saveStory: (story) => ipcRenderer.invoke('stories:save', story),
  deleteStory: (story) => ipcRenderer.invoke('stories:delete', story),
  importStoryImage: (story, blockId) => ipcRenderer.invoke('stories:importImage', story, blockId),
  removeStoryImage: (story, assetPath) => ipcRenderer.invoke('stories:removeImage', story, assetPath),
  getLibraryCharacters: () => ipcRenderer.invoke('library:getCharacters'),
  getLibraryCharacterSummaries: () => ipcRenderer.invoke('library:getCharacterSummaries'),
  getCharacter: (characterId) => ipcRenderer.invoke('library:getCharacter', characterId),
  generateAssetCompletenessReport: () => ipcRenderer.invoke('library:generateAssetCompletenessReport'),
  saveCharacter: (character) => ipcRenderer.invoke('library:saveCharacter', character),
  deleteCharacter: (character) => ipcRenderer.invoke('library:deleteCharacter', character),
  importAsset: (character, assetType) => ipcRenderer.invoke('library:importAsset', character, assetType),
  selectImageForCrop: () => ipcRenderer.invoke('library:selectImageForCrop'),
  saveCroppedAvatar: (character, imageDataUrl, fileName) =>
    ipcRenderer.invoke('library:saveCroppedAvatar', character, imageDataUrl, fileName),
  removeAsset: (character, assetType, assetPath) => ipcRenderer.invoke('library:removeAsset', character, assetType, assetPath),
  importCharacterDirectory: (sourceDirectory) => ipcRenderer.invoke('library:importCharacterDirectory', sourceDirectory),
});
